
services:
  tts-backend:
    image: tts-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tts-backend
    restart: always
    env_file:
      - ../tts.env
    environment:
      PROJECT_NAME: tts
      DB_HOST: mysql_db
      DB_PORT: "3306"
      DB_NAME: tts_db
    depends_on:
      mysql_db:
        condition: service_healthy
    volumes:
      - ../server_data/tts_data:/app/data
    networks:
      - web
